name: .NET Core

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: windows-latest
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Publish application
      run: dotnet publish -c Release -r win-x64 -o publish/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      if: contains(github.ref, "tags")
      with:
        # Artifact name
        name: Crabtopus.exe
        # Directory containing files to upload
        path: publish/Crabtopus.exe
